FROM python:3.11-slim
WORKDIR /app
COPY requirements /app/requirements
RUN pip install --no-cache-dir -r requirements
COPY app.py /app/
EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]